### ISSUE TITLE
不知道大佬有没有看过FCAnet: Frequency Channel Attention Networks

### ISSUE THREAD

**Issue by zuoyanwangmuyan** [MzeroMiko/vHeat#3]
不知道大佬有没有看过FCAnet: Frequency Channel Attention Networks，论文里面证明了GAP是2D DCT的一种形式，感觉和大佬的hco有所类似，个人理解hco是通道注意力的一种形式

**Comment by feufhd** [comment]
感谢关注！大佬不敢当，我认为是这样的，不过区别在于给频域注意力加上了物理热传导方程/模型的先验。您也可以看下E.4部分跟GFNet的对比
