### ISSUE TITLE
代码疑惑求解

### ISSUE THREAD

**Issue by Txr7** [MzeroMiko/vHeat#6]
x = F.conv1d(x.contiguous().view(B, H, -1), weight_cosn.contiguous().view(N, H, 1))
x = F.conv1d(x.contiguous().view(-1, W, C), weight_cosm.contiguous().view(M, W, 1)).contiguous().view(B, N, M,-1)
和
x = F.conv1d(x.contiguous().view(B, N, -1), weight_cosn.t().contiguous().view(H, N, 1))
x = F.conv1d(x.contiguous().view(-1, M, C), weight_cosm.t().contiguous().view(W, M, 1)).contiguous().view(B, H,  W, -1)

这就是傅里叶变换和反傅里叶变换的实现吗？

**Comment by feufhd** [comment]
您好！这两部分分别是DCT和IDCT的实现，也可以用torch.einsum()实现如下：

**Comment by feufhd** [comment]
您好！这两部分分别是DCT和IDCT的实现，也可以用torch.einsum()来实现，如下：
x = torch.einsum("bhwc,nh,mw -> bnmc", x, weight_cosn, weight_cosm) #DCT
x = torch.einsum("bnmc,nh,mw -> bhwc", x, weight_cosn, weight_cosm) # IDCT
这样比较好理解，但是现在采用的conv1d的实现速度更快

**Comment by Txr7** [comment]
非常感谢您的回复和讲解！
